## static_countries
UPDATE static_countries SET cn_short_cs='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_cs='Spojené arabské emiráty' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_cs='Afghánistán' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_cs='Antigua a Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_cs='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_cs='Albánie' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_cs='Arménie' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_cs='Nizozemské Antily' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_cs='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_cs='Antarktida' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_cs='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_cs='Americká Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_cs='Rakousko' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_cs='Austrálie' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_cs='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_cs='Ázerbájdžán' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_cs='Bosna a Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_cs='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_cs='Bangladéš' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_cs='Belgie' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_cs='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_cs='Bulharsko' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_cs='Bahrajn' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_cs='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_cs='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_cs='Bermudy' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_cs='Sultanát Brunej' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_cs='Bolívie' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_cs='Brazílie' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_cs='Bahamy' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_cs='Bhútán' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_cs='Bouvetův ostrov' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_cs='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_cs='Bělorusko' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_cs='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_cs='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_cs='Kokosové (Keelingovy) ostrovy' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_cs='Demokratická republika Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_cs='Středoafrická republika' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_cs='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_cs='Švýcarsko' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_cs='Pobřeží slonoviny' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_cs='Cookovy ostrovy' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_cs='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_cs='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_cs='Čína' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_cs='Kolumbie' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_cs='Kostarika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_cs='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_cs='Kapverdské ostrovy' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_cs='Vánoční ostrov' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_cs='Kypr' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_cs='Česká republika' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_cs='Německo' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_cs='Džibutsko' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_cs='Dánsko' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_cs='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_cs='Dominikánská republika' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_cs='Alžírsko' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_cs='Ekvádor' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_cs='Estonsko' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_cs='Egypt' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_cs='Západní Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_cs='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_cs='Španělsko' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_cs='Etiopie' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_cs='Finsko' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_cs='Fidži' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_cs='Falklandy' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_cs='Mikronésie' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_cs='Faerské ostrovy' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_cs='Francie' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_cs='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_cs='Velká Británie' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_cs='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_cs='Gruzie' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_cs='Francouzská Guayana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_cs='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_cs='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_cs='Grónsko' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_cs='Gambie' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_cs='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_cs='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_cs='Rovníková Guinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_cs='Řecko' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_cs='Jižní Georgie a Jižní Sandwichovy ostrovy' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_cs='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_cs='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_cs='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_cs='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_cs='Zvláštní správní oblast Čínské lidové republiky Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_cs='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_cs='Chorvatsko' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_cs='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_cs='Maďarsko' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_cs='Indonésie' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_cs='Irsko' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_cs='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_cs='Indie' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_cs='Britské indickooceánské území' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_cs='Irák' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_cs='Írán' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_cs='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_cs='Itálie' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_cs='Jamajka' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_cs='Jordánsko' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_cs='Japonsko' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_cs='Keňa' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_cs='Kyrgyzstán' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_cs='Kambodža' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_cs='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_cs='Komory' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_cs='Svatý Kryštof a Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_cs='Korejská lidově demokratická republika' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_cs='Korejská republika' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_cs='Kuvajt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_cs='Kajmanské ostrovy' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_cs='Kazachstán' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_cs='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_cs='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_cs='Svatá Lucie' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_cs='Lichtenštejnsko' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_cs='Srí Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_cs='Libérie' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_cs='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_cs='Litva' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_cs='Lucembursko' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_cs='Lotyšsko' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_cs='Libye' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_cs='Maroko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_cs='Monako' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_cs='Moldavská republika' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_cs='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_cs='Marshallovy ostrovy' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_cs='Makedonie' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_cs='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_cs='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_cs='Mongolsko' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_cs='Zvláštní správní oblast Čínské lidové republiky Macao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_cs='Severní Mariany' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_cs='Martinik' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_cs='Mauritánie' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_cs='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_cs='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_cs='Mauricius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_cs='Maledivy' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_cs='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_cs='Mexiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_cs='Malajsie' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_cs='Mosambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_cs='Namibie' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_cs='Nová Kaledonie' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_cs='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_cs='Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_cs='Nigérie' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_cs='Nikaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_cs='Nizozemsko' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_cs='Norsko' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_cs='Nepál' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_cs='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_cs='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_cs='Nový Zéland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_cs='Omán' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_cs='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_cs='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_cs='Francouzská Polynésie' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_cs='Papua-Nová Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_cs='Filipíny' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_cs='Pákistán' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_cs='Polsko' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_cs='Saint Pierre a Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_cs='Pitcairnovy ostrovy' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_cs='Portoriko' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_cs='Portugalsko' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_cs='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_cs='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_cs='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_cs='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_cs='Rumunsko' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_cs='Ruská federace' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_cs='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_cs='Saúdská Arábie' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_cs='Šalamounovy ostrovy' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_cs='Seychely' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_cs='Súdán' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_cs='Švédsko' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_cs='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_cs='Svatá Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_cs='Slovinsko' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_cs='Špicberky a Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_cs='Slovensko' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_cs='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_cs='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_cs='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_cs='Somálsko' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_cs='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_cs='Svatý Tomáš a Princův ostrov' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_cs='Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_cs='Sýrie' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_cs='Svazijsko' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_cs='Turks a Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_cs='Čad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_cs='Francouzská jižní a antarktická území' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_cs='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_cs='Thajsko' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_cs='Tádžikistán' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_cs='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_cs='Turkmenistán' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_cs='Tunisko' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_cs='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_cs='Východní Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_cs='Turecko' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_cs='Trinidad a Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_cs='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_cs='Tchaj-wan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_cs='Tanzanie' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_cs='Ukrajina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_cs='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_cs='Americká Oceánie' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_cs='Spojené státy americké' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_cs='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_cs='Uzbekistán' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_cs='Vatikán' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_cs='Svatý Vincenc a Grenadiny' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_cs='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_cs='Britské Panenské ostrovy' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_cs='Americké Panenské ostrovy' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_cs='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_cs='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_cs='Wallis a Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_cs='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_cs='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_cs='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_cs='Jihoafrická republika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_cs='Zambie' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_cs='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_cs='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_cs='Srbsko a Černá Hora' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_cs='Ålandy' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_cs='Heardův ostrov a McDonaldovy ostrovy' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_cs='Černá Hora' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_cs='Srbsko' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_cs='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_cs='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_cs='Ostrov Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_cs='Svatý Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_cs='Svatý Bartoloměj' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_cs='Bonaire, Svatý Eustach a Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_cs='Curaçao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_cs='Svatý Martin' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_cs='Jižní Súdán' WHERE cn_iso_2='SS';

UPDATE static_countries SET cn_official_name_cs = cn_short_cs WHERE cn_official_name_cs='' OR cn_official_name_cs IS NULL;